export const styles = {
    page: {
        minHeight: "100vh",
        background: "linear-gradient(180deg, #f0f8fb 0%, #e6f5fa 100%)",
        fontFamily: "'Segoe UI', '-apple-system', 'BlinkMacSystemFont', 'Roboto', sans-serif",
    },
    // ================= HEADER ================= 
    // ================= HEADER ================= 
    header: {
        background: "#082f3d", // Deep teal/navy
        padding: "0 40px",
        position: "sticky",
        top: 0,
        zIndex: 1000,
        boxShadow: "none",
        borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
        height: "80px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    headerContent: {
        width: "100%",
        maxWidth: "1400px",
        display: "flex",
        alignItems: "center",
        gap: "40px", // Spacing between Logo and Nav
    },
    logoSection: {
        display: "flex",
        alignItems: "center",
        gap: "12px",
        cursor: "pointer",
    },
    logoIcon: {
        width: "32px",
        height: "32px",
        color: "#1abc9c",
    },
    brandText: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
    },
    brandName: {
        fontSize: "24px",
        fontWeight: "700",
        color: "#fff",
        lineHeight: "1",
        letterSpacing: "-0.5px",
        fontFamily: "'Inter', sans-serif",
    },
    brandTagline: {
        fontSize: "9px",
        color: "#1abc9c",
        fontWeight: "600",
        letterSpacing: "1px",
        marginTop: "3px",
        textTransform: "uppercase",
    },
    nav: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
        marginLeft: "auto", // Pushes Nav to the right
    },
    navItem: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        color: "#b0bec5",
        textDecoration: "none",
        fontSize: "15px",
        fontWeight: "500",
        cursor: "pointer",
        transition: "all 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        background: "transparent",
        border: "none",
        padding: "10px 20px",
        borderRadius: "30px",
    },
    navItemActive: {
        background: "#0f4c5c", // Dark teal pill
        color: "#1abc9c",
        padding: "10px 24px",
        borderRadius: "30px",
        fontWeight: "600",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        gap: "8px",
        border: "none",
        fontSize: "15px",
    },
    rightSection: {
        display: "flex",
        alignItems: "center",
        gap: "24px",
    },
    separator: {
        height: "24px",
        width: "1px",
        background: "rgba(255, 255, 255, 0.15)",
    },
    navBtn: {
        background: "transparent",
        border: "none",
        color: "rgba(255, 255, 255, 0.8)",
        fontWeight: 600,
        cursor: "pointer",
        fontSize: "15px",
        padding: "8px",
        transition: "all 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        display: "flex",
        alignItems: "center",
        gap: "8px",
        position: "relative",
    },
    userBtn: {
        background: "transparent",
        border: "none",
        color: "rgba(255, 255, 255, 0.9)",
        cursor: "pointer",
        padding: "8px",
        transition: "all 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        fontWeight: 600,
        fontSize: "15px",
    },
    cartBadge: {
        background: "#e74c3c",
        color: "#fff",
        fontSize: "10px",
        fontWeight: "700",
        height: "16px",
        minWidth: "16px",
        padding: "0 4px",
        borderRadius: "10px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        position: "absolute",
        top: "-2px",
        right: "-6px",
        border: "1px solid #082f3d",
    },
    cartIconWrapper: {
        position: "relative",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },

    // ================= HERO ================= 
    hero: {
        position: "relative",
        minHeight: "100vh",
        marginTop: "-80px", // Pull behind header
        paddingTop: "160px",
        paddingBottom: "100px",
        display: "flex",
        alignItems: "center",
        background: "url('https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=2070&auto=format&fit=crop')", // High quality warehouse
        backgroundSize: "cover",
        backgroundPosition: "center",
    },
    heroOverlay: {
        position: "absolute",
        inset: 0,
        background: "linear-gradient(90deg, rgba(8, 47, 61, 0.95) 0%, rgba(8, 47, 61, 0.85) 50%, rgba(8, 47, 61, 0.4) 100%)",
    },
    heroContent: {
        position: "relative",
        zIndex: 1,
        width: "100%",
        maxWidth: "1400px",
        margin: "0 auto",
        padding: "0 40px",
    },
    heroBadge: {
        display: "inline-flex",
        alignItems: "center",
        gap: "10px",
        background: "rgba(26, 188, 156, 0.15)",
        border: "1px solid rgba(26, 188, 156, 0.3)",
        padding: "10px 24px",
        borderRadius: "30px",
        color: "#1abc9c",
        fontWeight: "800",
        fontSize: "13px",
        letterSpacing: "1px",
        marginBottom: "36px",
        backdropFilter: "blur(4px)",
    },
    heroTitle: {
        fontSize: "72px",
        fontWeight: "900",
        color: "#fff",
        lineHeight: "1.1",
        marginBottom: "24px",
        letterSpacing: "-2px",
        maxWidth: "900px",
    },
    highlight: {
        color: "#1abc9c",
    },
    heroSubtitle: {
        fontSize: "20px",
        color: "#b0bec5",
        lineHeight: "1.6",
        maxWidth: "650px",
        marginBottom: "50px",
        fontWeight: "500",
    },
    heroButtons: {
        display: "flex",
        gap: "20px",
    },
    primaryBtn: {
        background: "#1abc9c",
        color: "#051419",
        padding: "18px 40px",
        borderRadius: "16px",
        fontSize: "16px",
        fontWeight: "700",
        border: "none",
        display: "flex",
        alignItems: "center",
        gap: "10px",
        boxShadow: "0 10px 30px rgba(26, 188, 156, 0.25)",
    },
    secondaryBtn: {
        background: "rgba(255, 255, 255, 0.05)",
        border: "1px solid rgba(255, 255, 255, 0.2)",
        color: "#fff",
        padding: "18px 40px",
        borderRadius: "16px",
        fontSize: "16px",
        fontWeight: "700",
        backdropFilter: "blur(4px)",
    },
    // ================= LOADING ================= 
    loadingOverlay: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: "rgba(0, 0, 0, 0.8)",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 2000,
        backdropFilter: "blur(10px)",
    },
    loadingSpinner: {
        width: "72px",
        height: "72px",
        border: "4px solid rgba(255, 255, 255, 0.12)",
        borderTop: "4px solid #3498db",
        borderRadius: "50%",
        animation: "spin 1.2s linear infinite",
        marginBottom: "24px",
        boxShadow: "0 0 30px rgba(52, 152, 219, 0.4)",
    },
    loadingText: {
        color: "#fff",
        fontSize: "16px",
        fontWeight: 800,
        textRendering: "optimizeLegibility",
    },
    container: {
        maxWidth: "1200px",
        margin: "0 auto",
        padding: "0 24px",
    },
    sectionHeader: {
        textAlign: "center",
        marginBottom: "70px",
    },
    sectionTitle: {
        fontSize: "3rem",
        fontWeight: 900,
        color: "#0a3a52",
        marginBottom: "18px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "16px",
        letterSpacing: "-0.5px",
        textRendering: "optimizeLegibility",
    },
    titleIcon: {
        fontSize: "2.8rem",
    },
    sectionSubtitle: {
        fontSize: "1.2rem",
        color: "#555",
        maxWidth: "700px",
        margin: "0 auto",
        lineHeight: 1.8,
        fontWeight: 500,
    },
    // ================= ANNOUNCEMENTS ================= 
    announcementsSection: {
        padding: "120px 0",
        background: "linear-gradient(180deg, #fff 0%, #f0f8fb 100%)",
    },
    announcementsGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(360px, 1fr))",
        gap: "35px",
    },
    announcementCard: {
        background: "linear-gradient(135deg, #fff 0%, #f8fcfd 100%)",
        borderRadius: "22px",
        padding: "35px",
        boxShadow: "0 12px 40px rgba(10, 58, 82, 0.1)",
        border: "1px solid rgba(52, 152, 219, 0.12)",
        transition: "all 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        animation: "slideUp 0.6s ease-out forwards",
        opacity: 0,
    },
    announcementHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: "22px",
    },
    announcementBadge: {
        background: "linear-gradient(135deg, #e6f5fa 0%, #d4ecf7 100%)",
        color: "#0d4a66",
        padding: "8px 18px",
        borderRadius: "20px",
        fontSize: "12px",
        fontWeight: 800,
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.06)",
        textRendering: "optimizeLegibility",
    },
    announcementPriority: {
        fontSize: "20px",
    },
    announcementTitle: {
        fontSize: "1.5rem",
        fontWeight: 900,
        color: "#0a3a52",
        marginBottom: "14px",
        letterSpacing: "-0.3px",
        textRendering: "optimizeLegibility",
    },
    announcementMessage: {
        color: "#2c3e50",
        lineHeight: 1.8,
        marginBottom: "22px",
        fontSize: "1.05rem",
        fontWeight: 500,
    },
    announcementFooter: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        paddingTop: "22px",
        borderTop: "1px solid rgba(52, 152, 219, 0.12)",
    },
    announcementTime: {
        color: "#999",
        fontSize: "12px",
        fontWeight: 700,
    },
    announcementTag: {
        background: "linear-gradient(135deg, #3498db 0%, #2980b9 100%)",
        color: "#fff",
        padding: "6px 14px",
        borderRadius: "15px",
        fontSize: "11px",
        fontWeight: 800,
        boxShadow: "0 6px 16px rgba(52, 152, 219, 0.25)",
        textRendering: "optimizeLegibility",
    },
    // ================= PRODUCTS ================= 
    productsSection: {
        padding: "120px 0",
        background: "linear-gradient(180deg, #f0f8fb 0%, #e6f5fa 100%)",
    },
    productsGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(290px, 1fr))",
        gap: "40px",
    },
    productCard: {
        background: "#fff",
        borderRadius: "22px",
        overflow: "hidden",
        boxShadow: "0 12px 40px rgba(10, 58, 82, 0.1)",
        transition: "all 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        cursor: "pointer",
        border: "1px solid rgba(52, 152, 219, 0.08)",
        animation: "slideUp 0.6s ease-out forwards",
        opacity: 0,
        position: "relative",
    },
    productImageContainer: {
        position: "relative",
        height: "260px",
        overflow: "hidden",
        background: "linear-gradient(135deg, #e8f4f8 0%, #d4ecf7 100%)",
    },
    productImageWrapper: {
        width: "100%",
        height: "100%",
        position: "relative",
        overflow: "hidden",
    },
    productImage: {
        width: "100%",
        height: "100%",
        objectFit: "cover",
        transition: "transform 0.6s cubic-bezier(0.34, 1.56, 0.64, 1)",
        backfaceVisibility: "hidden",
    },
    imageOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: "linear-gradient(135deg, rgba(10, 58, 82, 0) 0%, rgba(10, 58, 82, 0.12) 100%)",
        opacity: 0,
        transition: "opacity 0.3s ease",
    },
    lowStockBadge: {
        position: "absolute",
        top: "16px",
        right: "16px",
        background: "linear-gradient(135deg, #e74c3c 0%, #c0392b 100%)",
        color: "#fff",
        padding: "8px 16px",
        borderRadius: "20px",
        fontSize: "12px",
        fontWeight: 800,
        boxShadow: "0 8px 24px rgba(231, 76, 60, 0.4)",
        backdropFilter: "blur(10px)",
        border: "1px solid rgba(255, 255, 255, 0.25)",
        textRendering: "optimizeLegibility",
    },
    bestsellerBadge: {
        position: "absolute",
        top: "16px",
        left: "16px",
        background: "linear-gradient(135deg, #1abc9c 0%, #16a085 100%)",
        color: "#fff",
        padding: "8px 16px",
        borderRadius: "20px",
        fontSize: "12px",
        fontWeight: 800,
        boxShadow: "0 8px 24px rgba(26, 188, 156, 0.4)",
        backdropFilter: "blur(10px)",
        border: "1px solid rgba(255, 255, 255, 0.3)",
        textRendering: "optimizeLegibility",
    },
    productContent: {
        padding: "28px",
    },
    productName: {
        fontSize: "1.3rem",
        fontWeight: 900,
        color: "#0a3a52",
        marginBottom: "10px",
        letterSpacing: "-0.2px",
        textRendering: "optimizeLegibility",
    },
    productCategory: {
        fontSize: "12px",
        color: "#2980b9",
        fontWeight: 800,
        marginBottom: "16px",
        display: "inline-block",
        background: "linear-gradient(135deg, #e6f5fa 0%, #d4ecf7 100%)",
        padding: "6px 16px",
        borderRadius: "15px",
        boxShadow: "0 3px 10px rgba(0, 0, 0, 0.05)",
        textRendering: "optimizeLegibility",
    },
    productFooter: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: "22px",
        paddingTop: "22px",
        borderTop: "1px solid rgba(52, 152, 219, 0.08)",
    },
    productPrice: {
        fontSize: "1.6rem",
        fontWeight: 900,
        background: "linear-gradient(135deg, #3498db 0%, #2980b9 100%)",
        WebkitBackgroundClip: "text",
        WebkitTextFillColor: "transparent",
        letterSpacing: "-0.3px",
        textRendering: "optimizeLegibility",
    },
    productStock: {
        fontSize: "12px",
        color: "#666",
        background: "linear-gradient(135deg, #e6f5fa 0%, #d4ecf7 100%)",
        padding: "6px 14px",
        borderRadius: "12px",
        fontWeight: 800,
        textRendering: "optimizeLegibility",
    },
    viewAllContainer: {
        textAlign: "center",
        marginTop: "80px",
    },
    viewAllBtn: {
        background: "transparent",
        border: "2px solid #3498db",
        color: "#3498db",
        padding: "18px 50px",
        borderRadius: "12px",
        fontSize: "15px",
        fontWeight: 800,
        cursor: "pointer",
        transition: "all 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        boxShadow: "0 6px 20px rgba(52, 152, 219, 0.15)",
        textRendering: "optimizeLegibility",
    },
    // ================= TESTIMONIALS ================= 
    testimonialsSection: {
        padding: "120px 0",
        background: "linear-gradient(180deg, #fff 0%, #f0f8fb 100%)",
    },
    testimonialsGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(360px, 1fr))",
        gap: "35px",
    },
    testimonialCard: {
        background: "linear-gradient(135deg, #f0f8fb 0%, #e6f5fa 100%)",
        borderRadius: "22px",
        padding: "40px",
        transition: "all 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        border: "1px solid rgba(52, 152, 219, 0.12)",
        boxShadow: "0 12px 40px rgba(10, 58, 82, 0.08)",
    },
    testimonialRating: {
        fontSize: "20px",
        marginBottom: "18px",
        letterSpacing: "3px",
    },
    testimonialContent: {
        fontSize: "1.15rem",
        fontStyle: "italic",
        color: "#2c3e50",
        marginBottom: "28px",
        lineHeight: 1.9,
        fontWeight: 500,
    },
    testimonialAuthor: {
        display: "flex",
        alignItems: "center",
        gap: "16px",
        paddingTop: "22px",
        borderTop: "1px solid rgba(52, 152, 219, 0.12)",
    },
    authorAvatar: {
        width: "52px",
        height: "52px",
        background: "linear-gradient(135deg, #3498db 0%, #2980b9 100%)",
        borderRadius: "50%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: "24px",
        color: "#fff",
        boxShadow: "0 6px 16px rgba(52, 152, 219, 0.3)",
        flexShrink: 0,
    },
    authorName: {
        fontWeight: 900,
        color: "#0a3a52",
        marginBottom: "3px",
        fontSize: "1.05rem",
        textRendering: "optimizeLegibility",
    },
    authorRole: {
        fontSize: "12px",
        color: "#666",
        margin: 0,
        fontWeight: 700,
    },
    emptyState: {
        textAlign: "center",
        padding: "120px 40px",
        background: "linear-gradient(135deg, #fff 0%, #f0f8fb 100%)",
        borderRadius: "26px",
        boxShadow: "0 12px 40px rgba(10, 58, 82, 0.1)",
        border: "2px dashed rgba(52, 152, 219, 0.25)",
    },
    emptyIcon: {
        fontSize: "96px",
        marginBottom: "24px",
        opacity: 0.65,
    },
    emptyTitle: {
        fontSize: "2.2rem",
        color: "#0a3a52",
        marginBottom: "12px",
        fontWeight: 900,
        letterSpacing: "-0.3px",
        textRendering: "optimizeLegibility",
    },
    emptyText: {
        color: "#666",
        fontSize: "1.15rem",
        maxWidth: "550px",
        margin: "0 auto",
        fontWeight: 500,
        lineHeight: 1.8,
    },
    // ================= CONTACT ================= 
    contactSection: {
        padding: "100px 0",
        background: "linear-gradient(180deg, #f0f8fb 0%, #fff 100%)",
        position: "relative",
    },
    contactGrid: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "60px",
        alignItems: "center",
        // Media queries removed as they are not supported in inline styles
    },
    contactInfo: {
        paddingRight: "40px",
    },
    contactDetails: {
        marginTop: "40px",
        display: "flex",
        flexDirection: "column",
        gap: "30px",
    },
    contactItem: {
        display: "flex",
        alignItems: "flex-start",
        gap: "18px",
    },
    contactIcon: {
        fontSize: "24px",
        background: "rgba(52, 152, 219, 0.1)",
        width: "50px",
        height: "50px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "12px",
    },
    contactLabel: {
        fontSize: "14px",
        color: "#999",
        marginBottom: "4px",
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: "0.5px",
    },
    contactText: {
        fontSize: "1.1rem",
        color: "#0a3a52",
        fontWeight: 600,
        margin: 0,
    },
    contactLink: {
        fontSize: "1.1rem",
        color: "#3498db",
        fontWeight: 600,
        textDecoration: "none",
    },
    contactFormWrapper: {
        background: "#fff",
        padding: "40px",
        borderRadius: "24px",
        boxShadow: "0 20px 60px rgba(10, 58, 82, 0.12)",
        border: "1px solid rgba(52, 152, 219, 0.15)",
    },
    formGroup: {
        marginBottom: "24px",
    },
    label: {
        display: "block",
        marginBottom: "8px",
        fontWeight: 600,
        color: "#0a3a52",
        fontSize: "14px",
    },
    input: {
        width: "100%",
        padding: "16px",
        borderRadius: "12px",
        border: "1px solid #e0e0e0",
        background: "#f8fbfc",
        fontSize: "15px",
        color: "#333",
        transition: "all 0.3s ease",
        fontFamily: "inherit",
    },
    textarea: {
        width: "100%",
        padding: "16px",
        borderRadius: "12px",
        border: "1px solid #e0e0e0",
        background: "#f8fbfc",
        fontSize: "15px",
        color: "#333",
        transition: "all 0.3s ease",
        fontFamily: "inherit",
        resize: "vertical",
    },
    submitBtn: {
        width: "100%",
        padding: "18px",
        background: "linear-gradient(135deg, #3498db 0%, #2980b9 100%)",
        color: "#fff",
        border: "none",
        borderRadius: "12px",
        fontSize: "16px",
        fontWeight: 700,
        cursor: "pointer",
        boxShadow: "0 10px 30px rgba(52, 152, 219, 0.3)",
        transition: "all 0.3s ease",
    }, ctaSection: {
        padding: "120px 24px",
        background: "linear-gradient(135deg, #0a3a52 0%, #0d4a66 100%)",
        color: "#fff",
        position: "relative",
        overflow: "hidden",
    },
    ctaGlowBg: {
        position: "absolute",
        top: "-50%",
        right: "-20%",
        width: "600px",
        height: "600px",
        background: "radial-gradient(circle, rgba(52, 152, 219, 0.25) 0%, transparent 70%)",
        borderRadius: "50%",
        filter: "blur(80px)",
        zIndex: 1,
    },
    ctaContent: {
        maxWidth: "900px",
        margin: "0 auto",
        textAlign: "center",
        position: "relative",
        zIndex: 2,
    },
    ctaTitle: {
        fontSize: "3.5rem",
        fontWeight: 900,
        marginBottom: "24px",
        lineHeight: 1.2,
        textShadow: "0 2px 12px rgba(0, 0, 0, 0.3)",
        letterSpacing: "-0.5px",
        textRendering: "optimizeLegibility",
    },
    ctaText: {
        fontSize: "1.35rem",
        opacity: 0.95,
        marginBottom: "45px",
        lineHeight: 1.9,
        textShadow: "0 1px 6px rgba(0, 0, 0, 0.2)",
        fontWeight: 500,
    },
    // ================= FOOTER ================= 
    footer: {
        background: "linear-gradient(180deg, #051419 0%, #030b10 100%)",
        color: "#fff",
        padding: "0",
        position: "relative",
        overflow: "hidden",
    },
    footerTopLine: {
        height: "4px",
        background: "linear-gradient(90deg, transparent 0%, #1abc9c 20%, #3498db 50%, #1abc9c 80%, transparent 100%)",
        boxShadow: "0 0 40px rgba(26, 188, 156, 0.6)",
    },
    footerContent: {
        maxWidth: "1200px",
        margin: "0 auto",
        padding: "100px 24px 70px",
        display: "grid",
        gridTemplateColumns: "1.5fr 2fr",
        gap: "90px",
    },
    footerLogo: {
        display: "flex",
        flexDirection: "column",
        gap: "24px",
    },
    footerLogoWrapper: {
        position: "relative",
        width: "90px",
        height: "90px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    footerLogoImg: {
        height: "90px",
        width: "90px",
        borderRadius: "16px",
        boxShadow: "0 16px 48px rgba(26, 188, 156, 0.3)",
        objectFit: "cover",
        zIndex: 1,
        transition: "all 0.3s ease",
        border: "2px solid rgba(255, 255, 255, 0.1)",
    },
    footerLogoGlow: {
        position: "absolute",
        inset: "-10px",
        background: "radial-gradient(circle, rgba(26, 188, 156, 0.4), transparent 70%)",
        borderRadius: "16px",
        filter: "blur(20px)",
        animation: "glow 4.5s cubic-bezier(0.4, 0, 0.6, 1) infinite",
    },
    footerTitle: {
        fontSize: "2.5rem",
        fontWeight: 900,
        background: "linear-gradient(135deg, #1abc9c 0%, #16a085 100%)",
        WebkitBackgroundClip: "text",
        WebkitTextFillColor: "transparent",
        margin: "0",
        letterSpacing: "0.5px",
        textRendering: "optimizeLegibility",
    },
    footerDescription: {
        fontSize: "15px",
        color: "rgba(255, 255, 255, 0.75)",
        lineHeight: 1.9,
        margin: 0,
        fontWeight: 500,
    },
    footerSocials: {
        display: "flex",
        gap: "16px",
        marginTop: "18px",
    },
    socialIcon: {
        fontSize: "24px",
        cursor: "pointer",
        transition: "all 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)",
        opacity: 0.8,
        display: "inline-flex",
        width: "48px",
        height: "48px",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "12px",
        background: "rgba(26, 188, 156, 0.12)",
        border: "1px solid rgba(26, 188, 156, 0.25)",
        textDecoration: "none",
        fontWeight: 800,
    },
    footerLinks: {
        display: "grid",
        gridTemplateColumns: "repeat(4, 1fr)",
        gap: "45px",
    },
    footerColumn: {
        display: "flex",
        flexDirection: "column",
        gap: "18px",
    },
    footerHeading: {
        fontSize: "14px",
        fontWeight: 900,
        marginBottom: "12px",
        color: "rgba(255, 255, 255, 0.98)",
        textTransform: "uppercase",
        letterSpacing: "1px",
        textRendering: "optimizeLegibility",
    },
    footerLink: {
        color: "rgba(255, 255, 255, 0.7)",
        textDecoration: "none",
        fontSize: "14px",
        transition: "all 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)",
        cursor: "pointer",
        fontWeight: 700,
    },
    footerBottom: {
        borderTop: "1px solid rgba(255, 255, 255, 0.1)",
        padding: "45px 24px",
        background: "linear-gradient(90deg, rgba(26, 188, 156, 0.06) 0%, transparent 50%, rgba(52, 152, 219, 0.06) 100%)",
    },
    footerBottomContent: {
        maxWidth: "1200px",
        margin: "0 auto",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        flexWrap: "wrap",
        gap: "35px",
    },
    copyright: {
        fontSize: "13px",
        color: "rgba(255, 255, 255, 0.6)",
        fontWeight: 700,
        margin: 0,
    },
    footerBadges: {
        display: "flex",
        gap: "16px",
        flexWrap: "wrap",
    },
    badge: {
        background: "linear-gradient(135deg, rgba(26, 188, 156, 0.25) 0%, rgba(52, 152, 219, 0.2) 100%)",
        color: "#1abc9c",
        padding: "7px 16px",
        borderRadius: "20px",
        fontSize: "11px",
        fontWeight: 900,
        border: "1px solid rgba(26, 188, 156, 0.35)",
        textRendering: "optimizeLegibility",
    },

    // ================= CONTACT SECTION (NEW) =================
    contactSection: {
        padding: "100px 20px",
        background: "linear-gradient(180deg, #fff 0%, #f0f8fb 100%)",
        display: "flex",
        justifyContent: "center",
    },
    contactContainer: {
        maxWidth: "800px",
        width: "100%",
        textAlign: "center",
    },
    contactHeader: {
        marginBottom: "50px",
    },
    contactSubtitle: {
        color: "#3498db",
        fontSize: "14px",
        fontWeight: "700",
        letterSpacing: "1.5px",
        textTransform: "uppercase",
        display: "block",
        marginBottom: "16px",
    },
    contactTitle: {
        fontSize: "2.8rem",
        color: "#0a3a52",
        marginBottom: "20px",
        fontWeight: "800",
        lineHeight: "1.2",
    },
    contactText: {
        fontSize: "1.1rem",
        color: "#666",
        maxWidth: "600px",
        margin: "0 auto",
        lineHeight: "1.6",
    },

    contactGrid: {
        display: "grid",
        gridTemplateColumns: "1fr 1.5fr",
        gap: "60px",
        alignItems: "start",
    },
    contactInfo: {
        textAlign: "left",
    },
    contactInfoItem: {
        display: "flex",
        alignItems: "flex-start",
        marginBottom: "40px",
    },
    contactIcon: {
        fontSize: "24px",
        background: "rgba(52, 152, 219, 0.1)",
        width: "50px",
        height: "50px",
        borderRadius: "12px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        marginRight: "20px",
        color: "#3498db",
    },
    contactInfoTitle: {
        fontSize: "1.2rem",
        color: "#0a3a52",
        marginBottom: "8px",
        fontWeight: "700",
    },
    contactInfoText: {
        fontSize: "1rem",
        color: "#666",
        lineHeight: "1.6",
    },
    contactForm: {
        width: "100%",
    },
    formGroup: {
        marginBottom: "24px",
        textAlign: "left",
    },
    label: {
        display: "block",
        marginBottom: "8px",
        color: "#0a3a52",
        fontWeight: "600",
        fontSize: "0.95rem",
    },
    input: {
        width: "100%",
        padding: "16px",
        borderRadius: "12px",
        border: "1px solid #e1e8ed",
        fontSize: "1rem",
        outline: "none",
        transition: "border-color 0.3s ease, box-shadow 0.3s ease",
        background: "#f8fbfc",
        ":focus": {
            borderColor: "#3498db",
            boxShadow: "0 0 0 4px rgba(52, 152, 219, 0.1)",
        }
    },
    textarea: {
        width: "100%",
        padding: "16px",
        borderRadius: "12px",
        border: "1px solid #e1e8ed",
        fontSize: "1rem",
        outline: "none",
        transition: "border-color 0.3s ease, box-shadow 0.3s ease",
        background: "#f8fbfc",
        resize: "vertical",
        minHeight: "150px",
        ":focus": {
            borderColor: "#3498db",
            boxShadow: "0 0 0 4px rgba(52, 152, 219, 0.1)",
        }
    },
    submitBtn: {
        background: "linear-gradient(135deg, #3498db 0%, #2980b9 100%)",
        color: "#fff",
        padding: "18px 40px",
        borderRadius: "12px",
        fontSize: "1.1rem",
        fontWeight: "700",
        border: "none",
        width: "100%",
        cursor: "pointer",
        transition: "transform 0.2s, box-shadow 0.2s",
        boxShadow: "0 10px 25px rgba(52, 152, 219, 0.3)",
        ":hover": {
            transform: "translateY(-2px)",
            boxShadow: "0 15px 35px rgba(52, 152, 219, 0.4)",
        },
        ":disabled": {
            opacity: 0.7,
            cursor: "not-allowed",
            transform: "none",
        }
    },
};
