# Generated by Django 6.0 on 2026-01-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='staff_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
