# Generated by Django 6.0 on 2026-02-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
