# Generated by Django 6.0 on 2026-02-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='idempotency_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
