# Generated by Django 6.0 on 2026-02-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_purchaseorder_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
