# Generated by Django 6.0 on 2026-02-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_product_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
    ]
