# Generated by Django 6.0 on 2026-02-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_staffattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffAttendance',
        ),
    ]
