# Generated by Django 6.0 on 2026-02-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_delete_staffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20),
        ),
    ]
